### ISSUE TITLE
Change Group field_primary_service_location to field_location for re-use

### ISSUE THREAD

**Issue by lgbridges** [Washington-County/COUNTY-DRUPAL#160]
We had discussed in a recent P&A meeting the idea of making the existing field_primary_service_location for Groups just be "field_location" so that other content types could re-use it -- the only difference being that it would be a single-value field for Group (to indicate primary location) and could be a multi-value field for other content types like Page.

Looking to gather any opinions or feedback about this before I turn this into a quick-burn story.

📣 @joshuami

**Comment by joshuami** [comment]
I'm not sure you'll be about to configure the field_groups to be both a single and multi-value field as field storage is shared even though the form display and field label can differ. It may need to be multi-value for both. 🤔

**Comment by lgbridges** [comment]
Hmm. Does that make a case for two separate field definitions?
