### ISSUE TITLE
Social media links still show up even if a group doesn't have values in them.

### ISSUE THREAD

**Issue by jlwcor** [Washington-County/COUNTY-DRUPAL#213]
Need to adjust the EVA views for social media links so that they are hidden if no value is set.

**Comment by mitziklambert** [comment]
This will be taken care of by PR #269. EVAs have been converted to Twig templates. There is conditional logic within the template to only display IF there is social media info in the corresponding field.

**Comment by mitziklambert** [comment]
This has been fixed as of WCOR-1217 (PR#269)

**Comment by mitziklambert** [comment]
This has been fixed as of WCOR-1217 (PR#269)
