### ISSUE TITLE
Reposition County Employee sign-in link.

### ISSUE THREAD

**Issue by lgbridges** [Washington-County/COUNTY-DRUPAL#248]
Positioning is awkward between password field and login button. Element just needs a `position: relative; top: 7rem;` etc.

![image](https://user-images.githubusercontent.com/17837170/139963353-c973837f-8b67-4408-8293-8044bf6a92e2.png)

**Comment by jlwcor** [comment]
@lgbridges we will be getting rid of the default login method in favor or utilizing only ADFS' SSO.
