### ISSUE TITLE
Drush can't trigger uli (admin one-time link) for dev site since PHP 8

### ISSUE THREAD

**Issue by lgbridges** [Washington-County/COUNTY-DRUPAL#326]
`drush @wcor.dev uli` doesn't work now. We may have to [upgrade to Drush 11 to mitigate](https://github.com/drush-ops/drush/issues/4914) even though it's pre-release.

**Comment by jlwcor** [comment]
@lgbridges it should still be working. It just includes an error message, but the URL still gets generated and printed.
