### ISSUE TITLE
SimpleSAMLphp is not working with PHP 8

### ISSUE THREAD

**Issue by if-nick** [Washington-County/COUNTY-DRUPAL#340]
When running the latest `develop` version of the site I see a white screen and— 

> The website encountered an unexpected error. Please try again later.
> Error: Failed opening required '/usr/share/php/Net/DNS2_wrapper.php' (include_path='/app/vendor/pear/archive_tar:/app/vendor/pear/console_getopt:/app/vendor/pear/pear-core-minimal/src:/app/vendor/pear/pear_exception:.:/usr/local/lib/php') in require() (line 65 of /app/simplesamlphp_files/config/config.php).

Recommendation:  we upgrade our SAML library to the latest version.

Or update Lando PHP build to include missing PHP modules.

It appears this is related to upgrading our environments to PHP 8. A quick fix is to run the following locally: 
```
lando composer remove drupal/simplesamlphp_auth && lando drush cr
```

In the SimpleSAMLphp issue queue I see a related comment [about PHP 8 support](https://github.com/simplesamlphp/simplesamlphp/issues/1461#issuecomment-836678827) and it looks to have been fixed in SimpleSAMLphp version [1.19.2](https://simplesamlphp.org/docs/1.19/simplesamlphp-changelog#section_3) The latest version is 1.19.4. 

This may not be easy to resolve. After spending an hour testing upgrades I see version conflicts. `composer show --all simplesamlphp/simplesamlphp` lists the dependencies the project has. One is `symfony/twig-bridge ^5.3`. However the latest Acquia BLT package has a lower version constraint `acquia/blt 13.2.1 requires symfony/twig-bridge ^3.3 -> satisfiable by symfony/twig-bridge[v3.4.47]`.  It may be possible patching BLT or creating an issue with that team. 

@joshuami , @cruno91

**Comment by if-nick** [comment]
It appears this is working fine on Acquia PHP 8.0.12.  

Now I believe we should update Lando to include missing PHP modules. Below is a screenshot showing Lando local vs. Acquia dev PHP modules.

![Screen Shot 2021-12-29 at 3 12 16 PM](https://user-images.githubusercontent.com/78449612/147709907-4c656d38-b9d3-46b7-90d8-50787ad66ae8.png)

**Comment by jlwcor** [comment]
By default, based on the configuration export files, simplesamlphp should be turned off in terms of actual usage in Drupal for non-production environments.

Just an FYI, I am able to run the latest develop build of the site on my local lando environment without any issue.

@if-nick have you run `lando rebuild` to see if that would solve build issues?

**Comment by if-nick** [comment]
That makes sense. Tried rebuilding with the latest from develop but am still needing to `lando composer remove drupal/simplesamlphp_auth && lando drush cr` to avoid it. Perhaps I can show this next week.

**Comment by jlwcor** [comment]
I'm beginning to suspect it may be a config split import issue.
By default for lando environments, it should automatically disable, not remove SIMPLESAMLPHP.

Does running `lando drush pm-uninstall simplesamlphp_auth `resolve the issue as opposed to composer remove?

Let's revisit next week.

**Comment by joshuami** [comment]
@if-nick @gatoona, I'm betting the documented workflow needs a bit of tweaking for the Lando users. 

When you do a `lando blt custom:catchup`, it will sometimes fail to do all it's steps if anything is amiss. (For example, if you haven't run a `composer install` before running that `blt` command the first time, it will also fail to complete the `drush deploy`. It's on `drush deploy`—or more specifically the `config import` step of a deploy that the simplesamlphp module is disabled. The database you get from the `blt` command still thinks it has simplesamlphp installed until that deploy successfully applies the config split. 

Let's see if we can get a couple minutes either Monday afternoon (tomorrow) or Tuesday. I think we can get this cleared up much faster with a quick screenshare. 😄
