### ISSUE TITLE
Media index not rebuilt after reindex cron

### ISSUE THREAD

**Issue by jmilden-git** [Washington-County/COUNTY-DRUPAL#343]
Trying to get new PDF view to display more than 4 files.  Have rerun the search index cron twice, but am not able to see more than the original 4 files.
https://www.washingtoncountyor.gov/finance/documents
Rebuilt media index and cleared cache:

Visit path: /admin/config/search/search-api/index/acquia_search_index_media
Click red Queue all items for reindexing button,
Confirm the action, then under Start indexing now section click the Index now button.

**Comment by lgbridges** [comment]
@jmilden-git -- I wonder if these documents I'm seeing in Support Services are the ones you're expecting to see -- if so, just need to change these documents' _Displayed in_ value to Finance.

![Capture](https://user-images.githubusercontent.com/17837170/148253060-4ffb881f-f392-4b67-a62a-158885d3bec6.PNG)
