### ISSUE TITLE
Menu items not showing in list

### ISSUE THREAD

**Issue by jmilden-git** [Washington-County/COUNTY-DRUPAL#371]
The dropdown for menu items opens with an empty list.  This started appearing at least a day ago.
![image](https://user-images.githubusercontent.com/58494273/149438717-e20ad452-6cc7-4e68-9a42-0a6ba0f5796b.png)

**Comment by jmilden-git** [comment]
@jlwcor This is still a problem.  Yesterday and today.  It's impacting the ability to configure content.

**Comment by jlwcor** [comment]
@joshuami https://www.drupal.org/project/cshs/issues/3258226
