### ISSUE TITLE
Parent group should be autocomplete unlimited

### ISSUE THREAD

**Issue by joshuami** [Washington-County/COUNTY-DRUPAL#67]

**Comment by gatoona** [comment]
Hey @joshuami can this issue be closed?

**Comment by joshuami** [comment]
Yeah, we can close. I checked and it looks like this was picked up in another story, but I'm realizing that we might need a follow up story to correct the form order to make displayed in appear in a consistent spot. Also, we missed that resource really should be part of a group. @lgbridges @gatoona , I'm adding that to the spec.
