### ISSUE TITLE
S3 upload issue when adding image in CD environment

### ISSUE THREAD

**Issue by lgbridges** [Washington-County/COUNTY-DRUPAL#84]
Creating a new image, selecting a GIF or PNG image in file field, and clicking _Save_ does not save the item. The edit page reloads, with the file field in red stating "Image field is required".  The log provides the following message.  Observed during testing of PR81.

> InvalidArgumentException: The HeadObject operation requires non-empty parameter: Bucket in Aws\InputValidationMiddleware->__invoke() (line 64 of /mnt/www/html/wcorode56/vendor/aws/aws-sdk-php/src/InputValidationMiddleware.php).

**Comment by gatoona** [comment]
Newly generated CD environments require the file holding the credentials to be manually pulled in from DEV.

Documentation on where that's stored is here: https://docs.acquia.com/resource/secrets/

**Comment by lgbridges** [comment]
I will try to distill the steps for this into our Drupal Development wiki for reference as the solution to this issue.

**Comment by lgbridges** [comment]
Jung was able to create a custom BLT command to handle this in #104 / #106. ``` blt custom:ode:uli [insert ode number] ``` will output a ODE one time login link. We should create a quick Wiki doc for our BLT custom commands at some point (although entering ``` blt ``` will get you the quick list of custom commands).
